### ISSUE TITLE
QPanda Cpp expamle中错误的编译参数

### ISSUE THREAD

**Issue by dwuggh** [S4Plus/QuantumCourse#8]
in https://github.com/OriginQ/QPanda-Example#linux and https://qpanda-tutorial.readthedocs.io/zh/latest/Tutorial.html#id10, compile parameter `-lTinyXML` should be added, and `-lGPUQGates` should be removed, or it is related to CUDA.

```bash
# ...
/usr/bin/ld: (.text.unlikely+0x3a9): undefined reference to `TiXmlString::nullrep_'
/usr/bin/ld: (.text.unlikely+0x3c3): undefined reference to `TiXmlNode::~TiXmlNode()'
/usr/bin/ld: ./pkg/qpanda-2-git/usr/lib//libQPanda2.a(QuantumMetadata.cpp.o): in function `QPanda::QuantumMetadata::~QuantumMetadata()':
(.text+0x2de): undefined reference to `vtable for TiXmlDocument'
/usr/bin/ld: (.text+0x2fa): undefined reference to `TiXmlString::nullrep_'
/usr/bin/ld: (.text+0x311): undefined reference to `TiXmlNode::~TiXmlNode()'
collect2: error: ld returned 1 exit status
```
adding `-lTinyXML` works fine.
I tend to think this is a common issue.

the full command:
```bash
g++ test.cpp -std=c++14 -fopenmp -I ./pkg/qpanda-2-git/usr/include/qpanda2/ -I ./pkg/qpanda-2-git/usr/include/qpanda2/ThirdParty/ -L ./pkg/qpanda-2-git/usr/lib/ -lComponents -lQAlg  -lQPanda2 -lantlr4 -lTinyXML -o test
```

environment: manjaro linux 20.1,  gcc 10.2.0

**Comment by shenzhi-git** [comment]
1. -lTinyXML的问题是因为您使用的是老版本的QPanda库和QPanda-excample，需要更新最新的QPanda库和QPanda excample。
2. -lGPUQGates 只有在支持cuda的版本中才需要使用。
具体的可以参照https://github.com/OriginQ/QPanda-Example中的介绍，感谢您对QPanda的使用和支持

**Comment by dwuggh** [comment]
>     1. -lTinyXML的问题是因为您使用的是老版本的QPanda库和QPanda-excample，需要更新最新的QPanda库和QPanda excample。
请问这是最近一周的commit修复的吗？我可以确认现在没有这个问题了。

>     2. -lGPUQGates 只有在支持cuda的版本中才需要使用。

https://qpanda-tutorial.readthedocs.io/zh/latest/Tutorial.html#id10 一点小问题，这里的文档没有CUDA的参数也包含 `-lGPUQGates`

**Comment by shenzhi-git** [comment]
是的，这个地方需要修改一下，非常感谢您的提醒

**Comment by dwuggh** [comment]
Thanks!
